/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author NGUYEN THANH THIEN
 */
public class Menu_Main extends javax.swing.JFrame {

    ConnectDataBaseTLMN_NetBeans kn = new ConnectDataBaseTLMN_NetBeans();
    Connection cn = kn.getConnectdatabase();
    
    
    /**
     * Creates new form Menu_Main
     */
    public Menu_Main() {
        initComponents();
        setResizable(true);
        setTitle("Tiến Lên Miền Nam(phiên bản Legend)");
        
        
        setLocationRelativeTo(null);
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnChoiNgay = new javax.swing.JButton();
        btnChon = new javax.swing.JButton();
        btnHD = new javax.swing.JButton();
        btnTHoat = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        btnChoiNgay.setBackground(new java.awt.Color(255, 255, 0));
        btnChoiNgay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnChoiNgay.setForeground(new java.awt.Color(0, 0, 255));
        btnChoiNgay.setText("CHƠI NGAY");
        btnChoiNgay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnChoiNgay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChoiNgay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChoiNgayMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChoiNgayMouseExited(evt);
            }
        });
        btnChoiNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoiNgayActionPerformed(evt);
            }
        });
        jPanel1.add(btnChoiNgay);
        btnChoiNgay.setBounds(320, 210, 150, 40);

        btnChon.setBackground(new java.awt.Color(255, 255, 0));
        btnChon.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnChon.setForeground(new java.awt.Color(0, 0, 255));
        btnChon.setText("CHỌN AVATAR");
        btnChon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnChon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChonMouseExited(evt);
            }
        });
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });
        jPanel1.add(btnChon);
        btnChon.setBounds(320, 270, 150, 40);

        btnHD.setBackground(new java.awt.Color(255, 255, 0));
        btnHD.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnHD.setForeground(new java.awt.Color(0, 0, 255));
        btnHD.setText("HƯỚNG DẪN");
        btnHD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnHD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHDMouseExited(evt);
            }
        });
        btnHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHDActionPerformed(evt);
            }
        });
        jPanel1.add(btnHD);
        btnHD.setBounds(320, 330, 150, 40);

        btnTHoat.setBackground(new java.awt.Color(255, 255, 0));
        btnTHoat.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnTHoat.setForeground(new java.awt.Color(0, 0, 255));
        btnTHoat.setText("THOÁT");
        btnTHoat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnTHoat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTHoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTHoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTHoatMouseExited(evt);
            }
        });
        btnTHoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTHoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnTHoat);
        btnTHoat.setBounds(320, 390, 150, 40);

        btnclose.setBackground(new java.awt.Color(60, 45, 81));
        btnclose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclose.setForeground(new java.awt.Color(0, 51, 51));
        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/exitout.png"))); // NOI18N
        btnclose.setBorder(null);
        btnclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclose.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncloseMouseExited(evt);
            }
        });
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose);
        btnclose.setBounds(710, 10, 50, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ima_TLMN/maxresdefault (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 770, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChoiNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoiNgayActionPerformed
        // TODO add your handling code here:
         setVisible(false);
         try {
                    Statement stm = cn.createStatement();
                    String temp2 = "UPDATE OTHER SET SOUND = 'off'";
                    stm.executeUpdate(temp2);
                    int count = 0;
                    ResultSet rs;
                    String[] temp = new String[30];
                    rs = stm.executeQuery("SELECT avatar FROM TABLETLMNTUYCHON");
                    while (rs.next()) {
                        temp[1] = rs.getString(1).trim();

                    }
                    rs = stm.executeQuery("SELECT chieucualuot FROM TABLETLMNTUYCHON");
                    while (rs.next()) {
                        temp[2] = rs.getString(1).trim();

                    }
                    rs = stm.executeQuery("SELECT soluongmay FROM TABLETLMNTUYCHON");
                    while (rs.next()) {
                        temp[3] = rs.getString(1).trim();

                    }
                    rs = stm.executeQuery("SELECT chedochoi FROM TABLETLMNTUYCHON");
                    while (rs.next()) {
                        temp[4] = rs.getString(1).trim();

                    }
                    rs = stm.executeQuery("SELECT nhac FROM TABLETLMNTUYCHON");
                    while (rs.next()) {
                        temp[5] = rs.getString(1).trim();

                    }
                    rs = stm.executeQuery("SELECT thoigiantremayrabai FROM TABLETLMNTUYCHON");
                    while (rs.next()) {
                        temp[6] = rs.getString(1).trim();

                    }
                    setVisible(false);
                    InGame frame = new InGame(temp[1], temp[2],
                            Integer.parseInt(temp[3]), temp[4], temp[5], Integer.parseInt(temp[6]));
                    frame.setVisible(true);
                } catch (SQLException ex) {
                    System.out.println(ex);
                }
    }//GEN-LAST:event_btnChoiNgayActionPerformed

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
                TuyChon n;
                try {
                    n = new TuyChon();
                    n.setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Menu_Main.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_btnChonActionPerformed

    private void btnTHoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTHoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnTHoatActionPerformed

    private void btnHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHDActionPerformed
        // TODO add your handling code here:
        setVisible(false);
                HuongDan n = new HuongDan();
                n.m();
    }//GEN-LAST:event_btnHDActionPerformed

    private void btnChoiNgayMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChoiNgayMouseEntered
        // TODO add your handling code here:
        
        btnChoiNgay.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_btnChoiNgayMouseEntered

    private void btnChoiNgayMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChoiNgayMouseExited
        // TODO add your handling code here:
        btnChoiNgay.setBackground(new Color(255,255,0));
    }//GEN-LAST:event_btnChoiNgayMouseExited

    private void btnChonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChonMouseEntered
        // TODO add your handling code here:
       
          btnChon.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_btnChonMouseEntered

    private void btnChonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChonMouseExited
        // TODO add your handling code here:
          btnChon.setBackground(new Color(255,255,0));
    }//GEN-LAST:event_btnChonMouseExited

    private void btnHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDMouseEntered
        // TODO add your handling code here:
        
        btnHD.setBackground(new Color(153,255,255));
        
    }//GEN-LAST:event_btnHDMouseEntered

    private void btnHDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHDMouseExited
        // TODO add your handling code here:
        btnHD.setBackground(new Color(255,255,0));
    }//GEN-LAST:event_btnHDMouseExited

    private void btnTHoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTHoatMouseEntered
        // TODO add your handling code here:
       
         btnTHoat.setBackground(new Color(153,255,255));
    }//GEN-LAST:event_btnTHoatMouseEntered

    private void btnTHoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTHoatMouseExited
        // TODO add your handling code here:
       
         btnTHoat.setBackground(new Color(255,255,0));
    }//GEN-LAST:event_btnTHoatMouseExited

    private void btncloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseEntered
        // TODO add your handling code here:
        ImageIcon Iconclose = new ImageIcon(getClass().getResource("/iconButtom/enterout.png"));
        btnclose.setIcon(Iconclose);
    }//GEN-LAST:event_btncloseMouseEntered

    private void btncloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseExited
        // TODO add your handling code here:
        ImageIcon Iconclose = new ImageIcon(getClass().getResource("/iconButtom/exitout.png"));
        btnclose.setIcon(Iconclose);
    }//GEN-LAST:event_btncloseMouseExited

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát game không không?","Thông báo",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
        }

    }//GEN-LAST:event_btncloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splashscreen.SplashScreenGame(null, true).setVisible(true);
                new Menu_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChoiNgay;
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnHD;
    private javax.swing.JButton btnTHoat;
    private javax.swing.JButton btnclose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
