/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.SQLProvider;
import POJO.NhanVien;
import Controller.PasswordRenderer;
import Controller.PasswordRendererShow;
import java.awt.Color;
import java.awt.Font;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author NGUYEN THANH THIEN
 */
public class frmThongtinNV extends javax.swing.JFrame {
    NhanVien nv = new NhanVien();
    Vector<String> header = new Vector<>();
    Vector data = new Vector();
    DefaultTableModel tblModel = new DefaultTableModel();
    /**
     * Creates new form frmThongtinNV
     */
    public frmThongtinNV() {
        initComponents();
        setTitle("THÔNG TIN NHÂN VIÊN");
         tblModel = (DefaultTableModel) this.tblThongtin.getModel();
        header.add("Tài khoản");
        header.add("Mật khẩu");
        LoadTable();
        tblModel.setDataVector(data, header);
        setLocationRelativeTo(null);
        
        tblThongtin.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,20));
        tblThongtin.getTableHeader().setOpaque(false);
        tblThongtin.getTableHeader().setBackground(new Color(32,136,203));
        tblThongtin.getTableHeader().setForeground(new Color(0,0,0));
        tblThongtin.setRowHeight(25);
        
        tblThongtin.setRowHeight(40);
        TableColumnModel columnModel = tblThongtin.getColumnModel();
        TableColumn column = columnModel.getColumn(0);
        column.setPreferredWidth(250);
        
        TableCellRenderer rendererFromHeader = tblThongtin.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        tblThongtin.getTableHeader().setDefaultRenderer(rendererFromHeader);
         DefaultTableCellRenderer renderer = new DefaultTableCellRenderer(); // tạo renderer
         renderer.setHorizontalAlignment(JLabel.CENTER); // thiết lập căn giữa cho dòng
        for (int i = 0; i < tblThongtin.getColumnCount(); i++) {
            tblThongtin.getColumnModel().getColumn(i).setCellRenderer(renderer); // sử dụng renderer cho tất cả các cột
        }

        TableColumn columnx = tblThongtin.getColumnModel().getColumn(1);
        columnx.setCellRenderer(new PasswordRenderer());
        
        btnidepass.hide();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThongtin = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnidepass = new javax.swing.JButton();
        btnshowpass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(60, 45, 81));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(60, 45, 81));

        tblThongtin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblThongtin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tblThongtin.setFillsViewportHeight(true);
        tblThongtin.setFocusable(false);
        tblThongtin.setRowHeight(30);
        tblThongtin.setSelectionBackground(new java.awt.Color(245, 101, 101));
        tblThongtin.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblThongtin);

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN NHÂN VIÊN");

        btnidepass.setBackground(new java.awt.Color(255, 255, 102));
        btnidepass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnidepass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-hide-25.png"))); // NOI18N
        btnidepass.setText("Hide password");
        btnidepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnidepassActionPerformed(evt);
            }
        });

        btnshowpass.setBackground(new java.awt.Color(255, 255, 102));
        btnshowpass.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnshowpass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-eye-25.png"))); // NOI18N
        btnshowpass.setText("Show password");
        btnshowpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowpassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnidepass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnshowpass, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnidepass)
                    .addComponent(btnshowpass))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnshowpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowpassActionPerformed

        tblModel.setRowCount(0);
        LoadTable();
        tblThongtin.updateUI();
    
        TableColumn columnx = tblThongtin.getColumnModel().getColumn(1);
        columnx.setCellRenderer(new PasswordRendererShow());
        
        btnshowpass.hide();
        btnidepass.setLocation(253, 60);
        btnidepass.show();
    }//GEN-LAST:event_btnshowpassActionPerformed

    private void btnidepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnidepassActionPerformed
        // TODO add your handling code here:
        tblModel.setRowCount(0);
        LoadTable();
        tblThongtin.updateUI();
      
        TableColumn columnx = tblThongtin.getColumnModel().getColumn(1);
        columnx.setCellRenderer(new PasswordRenderer());
       
        btnidepass.hide();
        btnshowpass.setLocation(253, 60);
        btnshowpass.show();
    }//GEN-LAST:event_btnidepassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmThongtinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmThongtinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmThongtinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmThongtinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmThongtinNV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnidepass;
    private javax.swing.JButton btnshowpass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblThongtin;
    // End of variables declaration//GEN-END:variables

    private void LoadTable() {
        try {
            SQLProvider data = new SQLProvider();
            data.open();
            CallableStatement cs = (data.getConnection()).prepareCall("{call thongtinnv()}");
            cs.execute();

            ResultSet rs = cs.getResultSet();
            while (rs.next()) {
                Vector v = new Vector();

                nv.setTenNV(rs.getString("Email"));
                nv.setMatkhau(rs.getString("Matkhau"));

                v.add(nv.getTenNV());
                v.add(nv.getMatkhau());
                this.data.add(v);
            }
            tblThongtin.updateUI();
        } catch (Exception e) {
        }
    }
    public void Center()
    {
        TableCellRenderer rendererFromHeader = tblThongtin.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        tblThongtin.getTableHeader().setDefaultRenderer(rendererFromHeader);
         DefaultTableCellRenderer renderer = new DefaultTableCellRenderer(); // tạo renderer
         renderer.setHorizontalAlignment(JLabel.CENTER); // thiết lập căn giữa cho dòng
        for (int i = 0; i < tblThongtin.getColumnCount(); i++) {
            tblThongtin.getColumnModel().getColumn(i).setCellRenderer(renderer); // sử dụng renderer cho tất cả các cột
        }
    }
    
}
