/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPN;

import DAO.SQLProvider;
import POJO.HangHoa;
import POJO.HoaDon;
import POJO.KhachHang;
import POJO.NhanVien;
import GUI.frmCTHoaDon;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;



/**
 *
 * @author NGUYEN THANH THIEN
 */
public class jpnHoaDon extends javax.swing.JPanel {
    DecimalFormat df = new DecimalFormat("#,###");
    private boolean isFormOpen = false;
    Vector<String> headerCT = new Vector<>();
    Vector dataCT = new Vector();
    DefaultTableModel tblModelCT = new DefaultTableModel();
    
    HoaDon hd = new HoaDon();
    KhachHang kh = new KhachHang();
    HangHoa hh = new HangHoa();
    NhanVien nv = new NhanVien();
    private String tennv;
    private int manv;

    public jpnHoaDon(String tennv, int manv) {
        initComponents();
        this.tennv = tennv;
        this.manv = manv;
       
        //----------------------------------------------------------------------------
        tblModelCT = (DefaultTableModel) this.tblCTHoaDon.getModel();
        
        headerCT.add("MÃ HÓA ĐƠN");
        headerCT.add("TÊN KHÁCH HÀNG");
        headerCT.add("NHÂN VIÊN LẬP");
        headerCT.add("THỜI GIAN");
        headerCT.add("TỔNG TIỀN");
        tblModelCT.setDataVector(dataCT, headerCT);
        LoadTableHoaDon();
        
        TableCellRenderer rendererFromHeader = tblCTHoaDon.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        tblCTHoaDon.getTableHeader().setDefaultRenderer(rendererFromHeader);
         DefaultTableCellRenderer renderer = new DefaultTableCellRenderer(); // tạo renderer
         renderer.setHorizontalAlignment(JLabel.CENTER); // thiết lập căn giữa cho dòng
        for (int i = 0; i < tblCTHoaDon.getColumnCount(); i++) {
            tblCTHoaDon.getColumnModel().getColumn(i).setCellRenderer(renderer); // sử dụng renderer cho tất cả các cột
        }
        
         TableColumnModel columnModel = tblCTHoaDon.getColumnModel();
        TableColumn column = columnModel.getColumn(0);
        TableColumn column1 = columnModel.getColumn(1);
        TableColumn column2 = columnModel.getColumn(2);
        TableColumn column3 = columnModel.getColumn(3); 
         TableColumn column4 = columnModel.getColumn(4); 

        column.setPreferredWidth(5);
        column1.setPreferredWidth(70);
        column2.setPreferredWidth(70);
        column3.setPreferredWidth(20);
        column4.setPreferredWidth(20);
        
        tblCTHoaDon.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,18));
        tblCTHoaDon.getTableHeader().setOpaque(false);
        tblCTHoaDon.getTableHeader().setBackground(new Color(32,136,203));
        tblCTHoaDon.getTableHeader().setForeground(new Color(0,0,0));
        tblCTHoaDon.setRowHeight(40);
        
        
        
        
        
    }
    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=QL_BanHang";
    String user = "sa";
    String pass = "123";
    Statement st;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblCTHoaDon = new javax.swing.JTable();
        btnTaoHoaDon = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimKiemHoaDon = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(60, 45, 81));
        setPreferredSize(new java.awt.Dimension(963, 751));

        tblCTHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblCTHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCTHoaDon.setEnabled(false);
        tblCTHoaDon.setFillsViewportHeight(true);
        tblCTHoaDon.setFocusable(false);
        tblCTHoaDon.setRowHeight(40);
        tblCTHoaDon.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblCTHoaDon.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblCTHoaDon);

        btnTaoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnTaoHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-create-order-65.png"))); // NOI18N
        btnTaoHoaDon.setText("TẠO HÓA ĐƠN");
        btnTaoHoaDon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTaoHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTaoHoaDonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTaoHoaDonMouseExited(evt);
            }
        });
        btnTaoHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHoaDonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tìm kiếm HD:");

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-restart-50.png"))); // NOI18N
        btnLamMoi.setText("LÀM MỚI ");
        btnLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HÓA ĐƠN THANH TOÁN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(356, 356, 356)
                .addComponent(btnTaoHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(btnLamMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTaoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHoaDonActionPerformed

        
          try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "Select *from NhanVien where MaNV = "+manv+"";
            PreparedStatement ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
           if(rs.next()) {
               frmCTHoaDon ct = new frmCTHoaDon(rs.getInt("MaNV"),rs.getString("TenNV"));
            
               

                    ct.setVisible(true);

                
               
            }    
        } catch (Exception e) {
        }     
    }//GEN-LAST:event_btnTaoHoaDonActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        tblModelCT.setRowCount(0);
        LoadTableHoaDon();
        tblCTHoaDon.updateUI();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTaoHoaDonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoHoaDonMouseEntered
        // TODO add your handling code here:
         btnTaoHoaDon.setBackground(new Color(0,255,255));
    }//GEN-LAST:event_btnTaoHoaDonMouseEntered

    private void btnTaoHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaoHoaDonMouseExited
        // TODO add your handling code here:
         btnTaoHoaDon.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnTaoHoaDonMouseExited


 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnTaoHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblCTHoaDon;
    private javax.swing.JTextField txtTimKiemHoaDon;
    // End of variables declaration//GEN-END:variables

    private void LoadTableHoaDon() {
        try {

            SQLProvider data = new SQLProvider();
            data.open();
            CallableStatement cs = (data.getConnection()).prepareCall("{call LoadHoaDon()}");
            cs.execute();
           
            ResultSet rs = cs.getResultSet();
            while (rs.next()) {
                Vector v = new Vector();

                hd.setMahd(rs.getInt("MaHD"));
                kh.setTenKH(rs.getString("TenKH"));
                nv.setTenNV(rs.getString("TenNV"));
                hd.setNgaylap(rs.getString("Ngaylap"));
                hd.setTongtien(rs.getFloat("TongTien"));

                v.add(hd.getMahd());
                v.add(kh.getTenKH());
                v.add(nv.getTenNV());
                v.add(hd.getNgaylap());
                v.add( df.format(hd.getTongtien()));

                dataCT.add(v);
            }
        } catch (Exception e) {
        }

    }
}
