/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPN;

import Controller.NumberOnlyFilter;
import DAO.DAO_HangHoa;
import DAO.DAO_LoaiHangHoa;
import DAO.SQLProvider;
import POJO.HangHoa;
import POJO.LoaiHangHoa;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author NGUYEN THANH THIEN
 */
public final class jpnHangHoa extends javax.swing.JPanel {
    DecimalFormat df = new DecimalFormat("#.###");
    Map< String, Integer> items = new HashMap<>();
    Vector<String> header = new Vector<>();
    Vector<String> headerloai = new Vector<>();
    Vector data = new Vector();
    Vector dataloai = new Vector();
    
    DefaultTableModel tblModel = new DefaultTableModel();
    DefaultTableModel tblModelloai = new DefaultTableModel();
    
    DecimalFormat decimalFormat = new DecimalFormat("#");
    /**
     * Creates new form jpnHangHoa
     */
    public jpnHangHoa() {
        initComponents();
        
        tblModel = (DefaultTableModel) this.tblHangHoa.getModel();
        tblModelloai = (DefaultTableModel) this.tblLoaiHangHoa.getModel();
        
        header.add("MÃ HH");
        header.add("TÊN HH");
        header.add("TÊN LOẠI");
        header.add("MÔ TẢ");
        header.add("SỐ LƯỢNG");
        header.add("GIÁ BÁN");
        
        headerloai.add("MÃ LOẠI HÀNG HÓA");
        headerloai.add("TÊN LOẠI HÀNG HÓA");
        
        LoadTableHangHoa();
        LoadTableLoaiHangHoa();
        LoadComboboxHangHoa();
        
        tblModel.setDataVector(data, header);
        
        tblModelloai.setDataVector(dataloai, headerloai);
        
        tblLoaiHangHoa.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,13));
        tblLoaiHangHoa.getTableHeader().setOpaque(false);
        tblLoaiHangHoa.getTableHeader().setBackground(new Color(32,136,203));
        tblLoaiHangHoa.getTableHeader().setForeground(new Color(0,0,0));
        tblLoaiHangHoa.setRowHeight(25);
        TableCellRenderer rendererFromHeader = tblHangHoa.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        tblHangHoa.getTableHeader().setDefaultRenderer(rendererFromHeader);
         DefaultTableCellRenderer renderer = new DefaultTableCellRenderer(); // tạo renderer
         renderer.setHorizontalAlignment(JLabel.CENTER); // thiết lập căn giữa cho dòng
        for (int i = 0; i < tblHangHoa.getColumnCount(); i++) {
            tblHangHoa.getColumnModel().getColumn(i).setCellRenderer(renderer); // sử dụng renderer cho tất cả các cột
        }
        
        tblHangHoa.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD,13));
        tblHangHoa.getTableHeader().setOpaque(false);
        tblHangHoa.getTableHeader().setBackground(new Color(32,136,203));
        tblHangHoa.getTableHeader().setForeground(new Color(0,0,0));
        tblHangHoa.setRowHeight(25);
        
        chondau();
        chondauloai();
        event();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaHH = new javax.swing.JTextField();
        cbbLoai = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtTenHH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMota = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMaloaiHH = new javax.swing.JTextField();
        txtTenloaiHH = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnThemMoi = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnThemMoiLoai = new javax.swing.JButton();
        btnLuuLoai = new javax.swing.JButton();
        btnXoaLoai = new javax.swing.JButton();
        btnSuaLoai = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHangHoa = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        btnSXtheoMaHH = new javax.swing.JButton();
        btnSXtheoten = new javax.swing.JButton();
        btnSXtheosl = new javax.swing.JButton();
        btnSXtheogia = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLoaiHangHoa = new javax.swing.JTable();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        setBackground(new java.awt.Color(60, 45, 81));
        setPreferredSize(new java.awt.Dimension(963, 749));

        jPanel1.setBackground(new java.awt.Color(60, 45, 81));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN HÀNG HÓA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã hàng:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Loại sản phẩm:");

        txtMaHH.setBackground(new java.awt.Color(246, 215, 184));
        txtMaHH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaHH.setEnabled(false);

        cbbLoai.setBackground(new java.awt.Color(246, 215, 184));
        cbbLoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbbLoai.setForeground(new java.awt.Color(255, 0, 0));
        cbbLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tên hàng:");

        txtTenHH.setBackground(new java.awt.Color(246, 215, 184));
        txtTenHH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenHHActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mô tả:");

        txtMota.setBackground(new java.awt.Color(246, 215, 184));
        txtMota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setBackground(new java.awt.Color(255, 102, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Số lượng:");

        txtSoluong.setBackground(new java.awt.Color(246, 215, 184));
        txtSoluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Giá bán:");

        txtGiaBan.setBackground(new java.awt.Color(246, 215, 184));
        txtGiaBan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbbLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)))
        );

        jPanel2.setBackground(new java.awt.Color(60, 45, 81));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN LOẠI HÀNG HÓA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 255, 255))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Mã loại:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tên loại");

        txtMaloaiHH.setEditable(false);
        txtMaloaiHH.setBackground(new java.awt.Color(246, 215, 184));
        txtMaloaiHH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaloaiHH.setEnabled(false);
        txtMaloaiHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaloaiHHActionPerformed(evt);
            }
        });

        txtTenloaiHH.setBackground(new java.awt.Color(246, 215, 184));
        txtTenloaiHH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenloaiHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenloaiHHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaloaiHH, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenloaiHH, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaloaiHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenloaiHH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(60, 45, 81));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THAO TÁC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(0, 255, 255))); // NOI18N

        btnThemMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-add-32.png"))); // NOI18N
        btnThemMoi.setText("NEW");
        btnThemMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiActionPerformed(evt);
            }
        });

        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-done-32.png"))); // NOI18N
        btnLuu.setText("LƯU");
        btnLuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-minus-32.png"))); // NOI18N
        btnXoa.setText("XÓA");
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-update-32.png"))); // NOI18N
        btnSua.setText("SỬA");
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemMoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(60, 45, 81));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THAO TÁC", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 13), new java.awt.Color(0, 255, 255))); // NOI18N

        btnThemMoiLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-add-32.png"))); // NOI18N
        btnThemMoiLoai.setText("NEW");
        btnThemMoiLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemMoiLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMoiLoaiActionPerformed(evt);
            }
        });

        btnLuuLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-done-32.png"))); // NOI18N
        btnLuuLoai.setText("LƯU");
        btnLuuLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLuuLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuLoaiActionPerformed(evt);
            }
        });

        btnXoaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-minus-32.png"))); // NOI18N
        btnXoaLoai.setText("XÓA");
        btnXoaLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoaiActionPerformed(evt);
            }
        });

        btnSuaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-update-32.png"))); // NOI18N
        btnSuaLoai.setText("SỬA");
        btnSuaLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLuuLoai, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                    .addComponent(btnThemMoiLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 31, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoaLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaLoai, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThemMoiLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLuuLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSuaLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(60, 45, 81));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BẢNG HÀNG HÓA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 255, 255))); // NOI18N

        tblHangHoa.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        tblHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblHangHoa.setFillsViewportHeight(true);
        tblHangHoa.setFocusable(false);
        tblHangHoa.setRowHeight(25);
        tblHangHoa.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblHangHoa.setSurrendersFocusOnKeystroke(true);
        tblHangHoa.getTableHeader().setReorderingAllowed(false);
        tblHangHoa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblHangHoaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHangHoaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHangHoa);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 204));
        jLabel5.setText("Tìm kiếm sản phẩm");

        jTextField5.setBackground(new java.awt.Color(246, 215, 184));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-search-24.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnSXtheoMaHH.setBackground(new java.awt.Color(255, 132, 132));
        btnSXtheoMaHH.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSXtheoMaHH.setForeground(new java.awt.Color(255, 255, 255));
        btnSXtheoMaHH.setText("Sắp xếp theo id");
        btnSXtheoMaHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXtheoMaHHActionPerformed(evt);
            }
        });

        btnSXtheoten.setBackground(new java.awt.Color(255, 132, 132));
        btnSXtheoten.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSXtheoten.setForeground(new java.awt.Color(255, 255, 255));
        btnSXtheoten.setText("Sắp xếp theo tên");
        btnSXtheoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXtheotenActionPerformed(evt);
            }
        });

        btnSXtheosl.setBackground(new java.awt.Color(255, 132, 132));
        btnSXtheosl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSXtheosl.setForeground(new java.awt.Color(255, 255, 255));
        btnSXtheosl.setText("Sắp xếp theo sl");
        btnSXtheosl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXtheoslActionPerformed(evt);
            }
        });

        btnSXtheogia.setBackground(new java.awt.Color(255, 132, 132));
        btnSXtheogia.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSXtheogia.setForeground(new java.awt.Color(255, 255, 255));
        btnSXtheogia.setText("Sắp xếp theo giá");
        btnSXtheogia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXtheogiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnSXtheoten)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSXtheosl, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSXtheogia)
                        .addGap(0, 51, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnSXtheoMaHH, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSXtheoMaHH)
                    .addComponent(btnSXtheoten)
                    .addComponent(btnSXtheosl)
                    .addComponent(btnSXtheogia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(60, 45, 81));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BẢNG LOẠI HÀNG HÓA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblLoaiHangHoa.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        tblLoaiHangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tblLoaiHangHoa.setFillsViewportHeight(true);
        tblLoaiHangHoa.setFocusable(false);
        tblLoaiHangHoa.setRowHeight(25);
        tblLoaiHangHoa.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblLoaiHangHoa.getTableHeader().setReorderingAllowed(false);
        tblLoaiHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiHangHoaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblLoaiHangHoa);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenHHActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtTenHHActionPerformed

    private void tblHangHoaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblHangHoaAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHangHoaAncestorAdded

    private void tblHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHangHoaMouseClicked

        int pos = tblHangHoa.getSelectedRow();
        this.txtMaHH.setText("" + tblModel.getValueAt(pos, 0));
        this.txtTenHH.setText((String) (tblHangHoa.getValueAt(pos, 1)));
        this.cbbLoai.setSelectedItem((String) (tblHangHoa.getValueAt(pos, 2)));
        this.txtMota.setText((String) (tblHangHoa.getValueAt(pos, 3)));
        this.txtSoluong.setText("" + tblModel.getValueAt(pos, 4));
        this.txtGiaBan.setText("" + decimalFormat.format(tblModel.getValueAt(pos, 5)));
        this.txtMaHH.setEnabled(false);
        
    }//GEN-LAST:event_tblHangHoaMouseClicked

    private void btnSXtheotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXtheotenActionPerformed
   
        Collections.sort(data, new Comparator<Vector>() {
            @Override
            public int compare(Vector o1, Vector o2) {
                String v1 = (String) o1.get(1);
                String v2 = (String) o2.get(1);
                return v1.compareTo(v2);
            }
        });
        tblHangHoa.clearSelection();
        tblHangHoa.updateUI();
    }//GEN-LAST:event_btnSXtheotenActionPerformed

    
    private void btnSXtheogiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXtheogiaActionPerformed
        
        Collections.sort(data, new Comparator<Vector>() {
            @Override
            public int compare(Vector o1, Vector o2) {
                Float v1 = (float) o1.get(5);
                Float v2 = (float) o2.get(5);
                return v1.compareTo(v2);
            }
        });
        tblHangHoa.clearSelection();
        tblHangHoa.updateUI();
    }//GEN-LAST:event_btnSXtheogiaActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed

        try {
            String tenHH = txtTenHH.getText().trim();
            if (KT_TenHH(tenHH)) {
                JOptionPane.showMessageDialog(this, "Tên hàng hóa đã tồn tại vui lòng kiểm tra lại");
            } else {
                int soluonghh = Integer.parseInt(txtSoluong.getText().trim());
                if (KiemTra_Gia() && KT_Soluong(soluonghh)) {
                    this.InsertHangHoa();
                } else {
                    JOptionPane.showMessageDialog(this, "Giá nhập hoặc số lượng không hợp lệ");
                    return;
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Không thể thêm hàng hóa vui lòng kiểm tra lại");
        }

    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        int pos = tblHangHoa.getSelectedRow();
        if (pos < 0) {

            JOptionPane.showMessageDialog(this, "Vui lòng chọn mã hàng hóa cần sửa");
        } else {
            int soluonghh = Integer.parseInt(txtSoluong.getText().trim());
            if (KiemTra_Gia() && KT_Soluong(soluonghh)) {

                this.UpdateHangHoa();

            } else {
                JOptionPane.showMessageDialog(this, "Giá | số lượng cần sửa không hợp lệ, vui lòng kiểm tra lại");
            }
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        
        try {
            int pos = tblHangHoa.getSelectedRow();
            
           
            if (pos < 0) {
                
                JOptionPane.showMessageDialog(this, "Vui lòng chọn mã hàng hóa cần xóa");
            } else {
                 int maHH = (int) tblHangHoa.getValueAt(pos, 0);
                if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa Mã hàng hóa :" + maHH, "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    this.DeleteHangHoa();
                    clear();
                }
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiActionPerformed
        // TODO add your handling code here:
        clear();
        
    }//GEN-LAST:event_btnThemMoiActionPerformed

    private void btnSXtheoMaHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXtheoMaHHActionPerformed
        // TODO add your handling code here:
         Collections.sort(data, new Comparator<Vector>() {
            @Override
            public int compare(Vector o1, Vector o2) {
                Integer v1 = (int) o1.get(0);
                Integer v2 = (int) o2.get(0);
                return v1.compareTo(v2);
            }
        });
        tblHangHoa.clearSelection();
        tblHangHoa.updateUI();
        
    }//GEN-LAST:event_btnSXtheoMaHHActionPerformed

    private void btnSXtheoslActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXtheoslActionPerformed
        // TODO add your handling code here:
        Collections.sort(data, new Comparator<Vector>() {
            @Override
            public int compare(Vector o1, Vector o2) {
                Integer v1 = (int) o1.get(4);
                Integer v2 = (int) o2.get(4);
                return v1.compareTo(v2);
            }
        });
        tblHangHoa.clearSelection();
        tblHangHoa.updateUI();
    }//GEN-LAST:event_btnSXtheoslActionPerformed

    private void txtMaloaiHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaloaiHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaloaiHHActionPerformed

    private void txtTenloaiHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenloaiHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenloaiHHActionPerformed

    private void btnThemMoiLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMoiLoaiActionPerformed
        // TODO add your handling code here:
       clearloai();
    }//GEN-LAST:event_btnThemMoiLoaiActionPerformed

    private void btnLuuLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuLoaiActionPerformed
        // TODO add your handling code here:
        String tenloai = txtTenloaiHH.getText().trim();
        if (tenloai.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên loại hàng không được để trống");

        } else {
            if (KT_TenloaiHH(tenloai)) {
                JOptionPane.showMessageDialog(this, "Tên loại hàng đã tồn tại, vui lòng xem lại");
                txtTenloaiHH.setText("");
                txtTenloaiHH.requestFocus();
            } else {
                this.InsertLoaiHangHoa();
                LoadComboboxHangHoa();
            }

        }


    }//GEN-LAST:event_btnLuuLoaiActionPerformed

    private void btnXoaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoaiActionPerformed
        // TODO add your handling code here:
        try {

            int pos = tblLoaiHangHoa.getSelectedRow();
           
            if (pos < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn mã loại cần xóa");
            }
            else {
                 int maLoaiHH = (int) tblLoaiHangHoa.getValueAt(pos, 0);
                 String maloaihh = String.valueOf(maLoaiHH);
                if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa Mã  loại hàng hóa :" + maLoaiHH, "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    if(KT_TonTaiLoaiHH(maloaihh))
                    {
                        JOptionPane.showMessageDialog(this, "Không thể xóa vì loại hàng này đang được sử dụng");
                    }
                    else
                    {
                        this.DeleteLoaiHangHoa();
                        LoadComboboxHangHoa();
                        clearloai();
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnXoaLoaiActionPerformed

    private void btnSuaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLoaiActionPerformed
        // TODO add your handling code here:
        try {
              int pos = tblLoaiHangHoa.getSelectedRow();
              
                 if (pos < 0) {
                JOptionPane.showMessageDialog(this, "Vui lòng chọn mã loại cần sửa");
            } else {
                 this.UpdateLoaiHangHoa();
                  LoadComboboxHangHoa();
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnSuaLoaiActionPerformed

    private void tblLoaiHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiHangHoaMouseClicked
        // TODO add your handling code here:
        int pos = tblLoaiHangHoa.getSelectedRow();
        this.txtMaloaiHH.setText("" + tblModelloai.getValueAt(pos, 0));
        this.txtTenloaiHH.setText((String) (tblLoaiHangHoa.getValueAt(pos, 1)));
        this.txtMaloaiHH.setEditable(false);
    }//GEN-LAST:event_tblLoaiHangHoaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnLuuLoai;
    private javax.swing.JButton btnSXtheoMaHH;
    private javax.swing.JButton btnSXtheogia;
    private javax.swing.JButton btnSXtheosl;
    private javax.swing.JButton btnSXtheoten;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaLoai;
    private javax.swing.JButton btnThemMoi;
    private javax.swing.JButton btnThemMoiLoai;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaLoai;
    private javax.swing.JComboBox<String> cbbLoai;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTable tblHangHoa;
    private javax.swing.JTable tblLoaiHangHoa;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaHH;
    private javax.swing.JTextField txtMaloaiHH;
    private javax.swing.JTextField txtMota;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenHH;
    private javax.swing.JTextField txtTenloaiHH;
    // End of variables declaration//GEN-END:variables
     public void DeleteHangHoa() throws IOException {

        int pos = tblHangHoa.getSelectedRow();
        int maHH = (int) tblHangHoa.getValueAt(pos, 0);

        boolean KT = DAO_HangHoa.DeleteHangHoa(maHH);
        if (KT) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        }
        tblModel.setRowCount(0);
        LoadTableHangHoa();
        tblHangHoa.updateUI();
    }

    public void UpdateHangHoa() {

        int pos = tblHangHoa.getSelectedRow();
        int maHH = (int) tblHangHoa.getValueAt(pos, 0);
        String TenHH = txtTenHH.getText().trim();
        int soluong = Integer.parseInt(txtSoluong.getText().trim());
        String Mota = txtMota.getText().trim();
        String nhomHH = (String) cbbLoai.getSelectedItem();
        int manhomHH = items.get(nhomHH);
        float giaban = Float.parseFloat(txtGiaBan.getText().trim());
        boolean KT = DAO_HangHoa.UpdateHangHoa(maHH, TenHH, manhomHH, Mota, soluong, giaban);
        if (KT) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        }
        tblModel.setRowCount(0);
        LoadTableHangHoa();
        tblHangHoa.updateUI();
    }
        
    public void InsertHangHoa() {
        
        String TenHH = txtTenHH.getText().trim();
        String Mota = txtMota.getText().trim();
        int soluong = Integer.parseInt(txtSoluong.getText().trim());
        String nhomHH = (String) cbbLoai.getSelectedItem();
        int manhomHH = items.get(nhomHH);
        float giaban = Float.parseFloat(txtGiaBan.getText().trim());

        boolean KT = DAO_HangHoa.InsertHangHoa(TenHH, manhomHH, Mota, soluong, giaban);
          if(KT)
        {
             JOptionPane.showMessageDialog(this, "Thêm thành công");
         }
        tblModel.setRowCount(0);
        LoadTableHangHoa();
        tblHangHoa.updateUI(); 
       
    }
     public void InsertLoaiHangHoa() {
        
        String TenLoai = txtTenloaiHH.getText().trim();
        
        boolean KT = DAO.DAO_LoaiHangHoa.InsertLoaiHangHoa(TenLoai);
        if(KT)
        {
             JOptionPane.showMessageDialog(this, "Thêm thành công");
         }
         tblModelloai.setRowCount(0);
         LoadTableLoaiHangHoa();
         tblLoaiHangHoa.updateUI();
    }
      public void UpdateLoaiHangHoa() {
        
        int pos = tblLoaiHangHoa.getSelectedRow();
        int maLoaiHH = (int) tblLoaiHangHoa.getValueAt(pos, 0);
        String TenLoai = txtTenloaiHH.getText().trim();
        
   
        boolean KT = DAO_LoaiHangHoa.UpdateLoaiHangHoa(maLoaiHH, TenLoai);
        if(KT)
        {
             JOptionPane.showMessageDialog(this, "Sửa thành công");
         }
         tblModelloai.setRowCount(0);
        LoadTableLoaiHangHoa();
        tblLoaiHangHoa.updateUI();
    }

    public void DeleteLoaiHangHoa() {

        int pos = tblLoaiHangHoa.getSelectedRow();
        int maLoaiHH = (int) tblLoaiHangHoa.getValueAt(pos, 0);

        boolean KT = DAO_LoaiHangHoa.DeleteLoaiHangHoa(maLoaiHH);
        if (KT) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        }
        tblModelloai.setRowCount(0);
        LoadTableLoaiHangHoa();
        tblLoaiHangHoa.updateUI();
    }

    private void LoadTableLoaiHangHoa() {
        Vector<LoaiHangHoa> dslhh = DAO_LoaiHangHoa.DS_LoaiHangHoa();
        for (LoaiHangHoa lhh : dslhh) {
            Vector v = new Vector();

            v.add(lhh.getMaLoai());
            v.add(lhh.getTenLoai());

            dataloai.add(v);
            txtMaloaiHH.setEditable(false);
        }
    }
    private void LoadTableHangHoa() {
        
        Vector<HangHoa> dshh = DAO_HangHoa.DS_HangHoa();
        for (HangHoa hh : dshh) {
            Vector v = new Vector();

            v.add(hh.getMaHH());
            v.add(hh.getTenHH());
            v.add(hh.getTenLoai());
            v.add(hh.getMoTa());
            v.add(hh.getSoluong());
            v.add(hh.getGiaBan());

            data.add(v);
        }
    }

    private void LoadComboboxHangHoa() {
        try {
            DefaultComboBoxModel ccbmodel = new DefaultComboBoxModel();
            cbbLoai.setModel(ccbmodel);
            String SQL = "SELECT *FROM LoaiHangHoa";
            SQLProvider data = new SQLProvider();
            data.open(); 
            ResultSet rs = data.executeQuery(SQL);
            while (rs.next()) {
                int id = rs.getInt("Maloai");
                String name = rs.getString("Tenloai");
                items.put(name, id);
                ccbmodel.addElement(name);
            }          
           data.close();
           
        } catch (SQLException e) {
            System.out.println("LỗI: " + e.getMessage());
        }
    }
    public boolean KiemTra_Gia()
    {
        String input = txtGiaBan.getText();
        if (input.matches("\\d+")) {
            return true;
        } else {
           return false;
        }
    }
    public  boolean KT_Soluong(int soluong)
    {
        if(soluong < 0)
            return false;
        return true;
    }
    public boolean KT_TenHH(String tenhh)
    {
        try {
            String sql = "Select * from HangHoa";
            SQLProvider kthh = new SQLProvider();
            kthh.open();
            ResultSet rs = kthh.executeQuery(sql);
            
            while (rs.next())
            {
                if(tenhh.equalsIgnoreCase(rs.getString("TenHH")))
                    return true;
            }
        } catch (Exception e) {
        }
        return false;
    }
    public boolean KT_TenloaiHH(String tenloaihh)
    {
        try {
            String sql = "Select * from LoaiHangHoa";
            SQLProvider kthh = new SQLProvider();
            kthh.open();
            ResultSet rs = kthh.executeQuery(sql);
            
            while (rs.next())
            {
                if(tenloaihh.equalsIgnoreCase(rs.getString("TenLoai")))
                    return true;
            }
        } catch (Exception e) {
        }
        return false;
    }
    public boolean KT_TonTaiLoaiHH(String maloai)
    {
        try {
            String sql = "Select * from HangHoa";
            SQLProvider kthh = new SQLProvider();
            kthh.open();
            ResultSet rs = kthh.executeQuery(sql);
            
            while (rs.next())
            {
                int maloaihh = rs.getInt("MaLoai");
                String maloaiHH = String.valueOf(maloaihh);
                if(maloai.equals(maloaiHH))
                    return true;
            }
        } catch (Exception e) {
        }
        return false;
    }
     public void chondau()
     {
          tblHangHoa.setRowSelectionInterval(0, 0);
        int pos = tblHangHoa.getSelectedRow();
        this.txtMaHH.setText("" + tblModel.getValueAt(pos, 0));
        this.txtTenHH.setText((String) (tblHangHoa.getValueAt(pos, 1)));
        this.cbbLoai.setSelectedItem((String) (tblHangHoa.getValueAt(pos, 2)));
        this.txtMota.setText((String) (tblHangHoa.getValueAt(pos, 3)));
        this.txtSoluong.setText("" + tblModel.getValueAt(pos, 4));
        this.txtGiaBan.setText("" + decimalFormat.format(tblModel.getValueAt(pos, 5)));
        this.txtMaHH.setEnabled(false);
     }
     public void chondauloai()
     {
        tblLoaiHangHoa.setRowSelectionInterval(0, 0);
        int pos = tblLoaiHangHoa.getSelectedRow();
        this.txtMaloaiHH.setText("" + tblModelloai.getValueAt(pos, 0));
        this.txtTenloaiHH.setText((String) (tblLoaiHangHoa.getValueAt(pos, 1)));
        this.txtMaloaiHH.setEditable(false);
     }

    private void event() {
        ((AbstractDocument) txtSoluong.getDocument()).setDocumentFilter(new NumberOnlyFilter());
        ((AbstractDocument) txtGiaBan.getDocument()).setDocumentFilter(new NumberOnlyFilter());
        
    }

    private void clear() {
        this.txtMaHH.setText("");
        this.txtTenHH.setText("");
        this.txtMota.setText("");
        this.txtGiaBan.setText("");
        txtSoluong.setText("");
        this.txtTenHH.requestFocus();
    }

    private void clearloai() {
         txtMaloaiHH.setText("");
        txtTenloaiHH.setText("");
        txtMaloaiHH.setEditable(false);
        txtTenloaiHH.requestFocus();
    }
   
}
