/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPN;

import DAO.DAO_NhanVien;
import POJO.NhanVien;
import Controller.RandomStringGenerator;
import DAO.SQLProvider;
import GUI.frmGuiMailNhanVien;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author NGUYEN THANH THIEN
 */
public final class jpnNhanVien extends javax.swing.JPanel {

    NhanVien nv = new NhanVien();
//    List<NhanVien> listNV = new ArrayList<>();
    Vector<String> header = new Vector<>();
    Vector data = new Vector();
    DefaultTableModel tblModel = new DefaultTableModel();

    /**
     * Creates new form jpnNhanVien
     */
    public jpnNhanVien() {
        initComponents();

        tblModel = (DefaultTableModel) this.tblNhanVien.getModel();
        header.add("MÃ NV");
        header.add("TÊN NHÂN VIÊN");
        header.add("GIỚI TÍNH");
        header.add("EMAIL");
        header.add("VAI TRÒ");
        header.add("TÌNH TRẠNG");
        LoadTableNhanVien();
        tblModel.setDataVector(data, header);

        tblNhanVien.setRowHeight(42);
        TableColumnModel columnModel = tblNhanVien.getColumnModel();

        TableColumn column = columnModel.getColumn(1);
        TableColumn column1 = columnModel.getColumn(3);
        TableColumn column2 = columnModel.getColumn(4);

        column.setPreferredWidth(200);
        column1.setPreferredWidth(240);
        column2.setPreferredWidth(35);

        TableCellRenderer rendererFromHeader = tblNhanVien.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        tblNhanVien.getTableHeader().setDefaultRenderer(rendererFromHeader);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer(); // tạo renderer
        renderer.setHorizontalAlignment(JLabel.CENTER); // thiết lập căn giữa cho dòng
        for (int i = 0; i < tblNhanVien.getColumnCount(); i++) {
            tblNhanVien.getColumnModel().getColumn(i).setCellRenderer(renderer); // sử dụng renderer cho tất cả các cột
        }

        buttonGroup1.add(rdoNhanVien);
        buttonGroup1.add(rdoQuanly);
        String[] Items = new String[]{"Nam", "Nữ"};
        DefaultComboBoxModel ccbmodel = new DefaultComboBoxModel(Items);
        cbbGender.setModel(ccbmodel);

        JTableHeader themp = tblNhanVien.getTableHeader();
        themp.setOpaque(false);
        themp.setFont(new Font("Segoe UI", Font.BOLD, 16));
        themp.setBackground(new Color(32, 136, 203));
        themp.setForeground(new Color(0, 0, 0));
        chondau();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTimkiem = new javax.swing.JTextField();
        btnThemNV = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdoQuanly = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        btnGuimail = new javax.swing.JButton();
        cbbGender = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(60, 45, 81));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(963, 751));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 170, 84));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã nhân viên:");

        txtMaNV.setEditable(false);
        txtMaNV.setBackground(new java.awt.Color(246, 215, 184));
        txtMaNV.setFont(new java.awt.Font("Segoe WP", 0, 22)); // NOI18N
        txtMaNV.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 170, 84));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tên nhân viên:");

        txtTenNV.setBackground(new java.awt.Color(246, 215, 184));
        txtTenNV.setFont(new java.awt.Font("Segoe WP", 0, 22)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 170, 84));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Email:");

        txtEmail.setBackground(new java.awt.Color(246, 215, 184));
        txtEmail.setFont(new java.awt.Font("Segoe WP", 0, 22)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 170, 84));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Gender");

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-add-48.png"))); // NOI18N
        btnThem.setText("THÊM NHÂN VIÊN");
        btnThem.setBorder(new javax.swing.border.MatteBorder(null));
        btnThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemMouseExited(evt);
            }
        });
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-update-48.png"))); // NOI18N
        btnSua.setText("  SỬA NHÂN VIÊN");
        btnSua.setBorder(new javax.swing.border.MatteBorder(null));
        btnSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSuaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSuaMouseExited(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-delete-48.png"))); // NOI18N
        btnXoa.setText("  XÓA NHÂN VIÊN");
        btnXoa.setBorder(new javax.swing.border.MatteBorder(null));
        btnXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXoaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXoaMouseExited(evt);
            }
        });
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tìm kiếm nhân viên:");

        txtTimkiem.setBackground(new java.awt.Color(246, 215, 184));
        txtTimkiem.setFont(new java.awt.Font("Segoe WP", 0, 18)); // NOI18N

        btnThemNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-save-48.png"))); // NOI18N
        btnThemNV.setText("  LƯU NHÂN VIÊN");
        btnThemNV.setBorder(new javax.swing.border.MatteBorder(null));
        btnThemNV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThemNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThemNVMouseExited(evt);
            }
        });
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 170, 84));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Vai trò:");

        jPanel1.setBackground(new java.awt.Color(60, 45, 81));

        rdoQuanly.setFont(new java.awt.Font("Segoe WP", 1, 18)); // NOI18N
        rdoQuanly.setForeground(new java.awt.Color(245, 139, 139));
        rdoQuanly.setText("Quản lý");

        rdoNhanVien.setFont(new java.awt.Font("Segoe WP", 1, 18)); // NOI18N
        rdoNhanVien.setForeground(new java.awt.Color(245, 139, 139));
        rdoNhanVien.setText("Nhân viên");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(rdoQuanly)
                .addGap(18, 18, 18)
                .addComponent(rdoNhanVien)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoQuanly)
                    .addComponent(rdoNhanVien))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuimail.setBackground(new java.awt.Color(255, 65, 255));
        btnGuimail.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        btnGuimail.setForeground(new java.awt.Color(255, 255, 255));
        btnGuimail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-mail-48.png"))); // NOI18N
        btnGuimail.setText("GỬI MAIL NHÂN VIÊN");
        btnGuimail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuimail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuimailActionPerformed(evt);
            }
        });

        cbbGender.setBackground(new java.awt.Color(246, 215, 184));
        cbbGender.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        cbbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblNhanVien.setFont(new java.awt.Font("Segoe WP Semibold", 0, 20)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tblNhanVien.setFillsViewportHeight(true);
        tblNhanVien.setFocusable(false);
        tblNhanVien.setRowHeight(30);
        tblNhanVien.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblNhanVien.setShowGrid(false);
        tblNhanVien.getTableHeader().setReorderingAllowed(false);
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-search-48.png"))); // NOI18N
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnGuimail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenNV)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(cbbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cbbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(7, 7, 7))
                    .addComponent(btnGuimail, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
       clearNV();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        // TODO add your handling code here:
        try {
            String mail = txtEmail.getText().trim();
            String TenNV = txtTenNV.getText().trim();
          
            if (TenNV.isEmpty()) {
               JOptionPane.showMessageDialog(this, "Tên nhân viên không được để trống");
            }
            else if(mail.isEmpty())
            {
                 JOptionPane.showMessageDialog(this, "Email không được để trống");
                
            }
            else if(!isValidEmail(mail))
            {
                 JOptionPane.showMessageDialog(this, "Email không hợp lệ");
                
            }
            else if(KT_TontaiEmail(mail))
            {
                JOptionPane.showMessageDialog(this, "Email đã tồn tại, vui lòng xem lại");
            }
            else {
                this.InsertNhanVien();
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnThemNVActionPerformed

    private void btnGuimailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuimailActionPerformed
        // TODO add your handling code here:
        frmGuiMailNhanVien gui = new frmGuiMailNhanVien();
        gui.setVisible(true);
    }//GEN-LAST:event_btnGuimailActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        try {
            this.txtTenNV.setEditable(true);
            // TODO add your handling code here:
            int pos = tblNhanVien.getSelectedRow();

            this.txtMaNV.setText("" + tblModel.getValueAt(pos, 0));
            this.txtTenNV.setText((String) (tblNhanVien.getValueAt(pos, 1)));
            this.cbbGender.setSelectedItem((String) (tblNhanVien.getValueAt(pos, 2)));
            this.txtEmail.setText((String) (tblNhanVien.getValueAt(pos, 3)));
            this.txtEmail.setEditable(true);
            int a = (int) tblModel.getValueAt(pos, 4);

            if (a == 1) {
                rdoQuanly.setSelected(true);
                rdoNhanVien.setSelected(false);

            } else {
                rdoQuanly.setSelected(false);
                rdoNhanVien.setSelected(true);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnThemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseExited
        // TODO add your handling code here:
//        btnThem.setBackground(new Color(32,136,203));
//        btnThem.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnThemMouseExited

    private void btnThemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemMouseEntered
        // TODO add your handling code here:
//        btnThem.setBackground(new Color(255,132,132));
//        btnThem.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnThemMouseEntered

    private void btnSuaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseEntered
        // TODO add your handling code here:
//         btnSua.setBackground(new Color(255,132,132));
//        btnSua.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnSuaMouseEntered

    private void btnXoaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseEntered
        // TODO add your handling code here:
//         btnXoa.setBackground(new Color(255,132,132));
//        btnXoa.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnXoaMouseEntered

    private void btnThemNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemNVMouseEntered
//        // TODO add your handling code here:
//         btnThemNV.setBackground(new Color(255,132,132));
//        btnThemNV.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_btnThemNVMouseEntered

    private void btnSuaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseExited
        // TODO add your handling code here:
//        btnSua.setBackground(new Color(32,136,203));
//        btnSua.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnSuaMouseExited

    private void btnXoaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXoaMouseExited
        // TODO add your handling code here:
//        btnXoa.setBackground(new Color(32,136,203));
//        btnXoa.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnXoaMouseExited

    private void btnThemNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemNVMouseExited
        // TODO add your handling code here:
//        btnThemNV.setBackground(new Color(32,136,203));
//        btnThemNV.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnThemNVMouseExited

    private void btnSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuaMouseClicked
        // TODO add your handling code here:
         int pos = tblNhanVien.getSelectedRow();
        if(pos < 0 )
        {
            JOptionPane.showMessageDialog(this, "Chưa chọn nhân viên cần sửa");
        }
        else
        {
            this.UpdateNhanVien();
        }
        
    }//GEN-LAST:event_btnSuaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int pos = tblNhanVien.getSelectedRow();
        if (pos < 0) {
            JOptionPane.showMessageDialog(this, "Chưa chọn nhân viên cần xóa");
        } else {
            try {
                int maHH = (int) tblNhanVien.getValueAt(pos, 0);
                if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa nhân viên số:" + maHH, "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    this.DeleteNhanVien();
                    clearNV();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);

            }
        }

    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuimail;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbbGender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoQuanly;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTimkiem;
    // End of variables declaration//GEN-END:variables

    public void UpdateNhanVien() {

        int vaitro;
        if (rdoNhanVien.isSelected()) {
            vaitro = 0;
        } else {
            vaitro = 1;
        }
        int pos = tblNhanVien.getSelectedRow();
        int maNV = (int) tblNhanVien.getValueAt(pos, 0);
        String TenNV = txtTenNV.getText().trim();
        String Email = txtEmail.getText().trim();
        String Gender = (String) cbbGender.getSelectedItem();

        boolean KT = DAO_NhanVien.UpdateNhanVien(maNV, TenNV, Gender, Email, vaitro);
        if (KT) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        }
        tblModel.setRowCount(0);
        LoadTableNhanVien();
        tblNhanVien.updateUI();

    }

    public void DeleteNhanVien() {

        try {
             int pos = tblNhanVien.getSelectedRow();
        int maHH = (int) tblNhanVien.getValueAt(pos, 0);

        boolean KT = DAO_NhanVien.DeleteNhanVien(maHH);
        if (KT) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        }
        tblModel.setRowCount(0);
        LoadTableNhanVien();
        tblNhanVien.updateUI();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, e);
        }
    }

    private void InsertNhanVien() {
        int vaitro;
        if (rdoNhanVien.isSelected()) {
            vaitro = 0;
        } else {

            vaitro = 1;
        }

        String password = RandomStringGenerator.generateRandomDigits(6);
        String TenNV = txtTenNV.getText().trim();
        String Email = txtEmail.getText().trim();
        String Gioitinh = (String) cbbGender.getSelectedItem();
        
        boolean kt = DAO_NhanVien.InsertNhanVien(TenNV, Gioitinh, Email, vaitro, password);
        if (kt) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        }
        tblModel.setRowCount(0);
        LoadTableNhanVien();
        tblNhanVien.updateUI();
    }

    private void LoadTableNhanVien() {
        Vector<NhanVien> dsnv = DAO_NhanVien.DS_NhanVien();
        for (NhanVien nv : dsnv) {
            Vector v = new Vector();
            v.add(nv.getMaNV());
            v.add(nv.getTenNV());
            v.add(nv.getGioiTinh());
            v.add(nv.getEmail());
            v.add(nv.getVaiTro());
            v.add(nv.getTinhTrang());
            data.add(v);
        }
    }

    public boolean isValidEmail(String email) {
        String regex = "^(?=.{1,64}@)[A-Za-z0-9_-]+(\\.[A-Za-z0-9_-]+)*@"
                + "[^-][A-Za-z0-9-]+(\\.[A-Za-z0-9-]+)*(\\.[A-Za-z]{2,})$";
        return email.matches(regex);
    }
    public boolean KT_TontaiEmail(String email)
    {
        try {
            String sql = "select *from NhanVien";
            SQLProvider ktemail = new SQLProvider();
            ktemail.open();
            ResultSet rs = ktemail.executeQuery(sql);
            while(rs.next())
            {
                if(email.equals(rs.getString("Email")))
                {
                    return true;
                }
            }
        } catch (Exception e) {
        }
        return false;
    }
       public void chondau()
     {
          tblNhanVien.setRowSelectionInterval(0, 0);
        try {
            this.txtTenNV.setEditable(true);
            // TODO add your handling code here:
            int pos = tblNhanVien.getSelectedRow();

            this.txtMaNV.setText("" + tblModel.getValueAt(pos, 0));
            this.txtTenNV.setText((String) (tblNhanVien.getValueAt(pos, 1)));
            this.cbbGender.setSelectedItem((String) (tblNhanVien.getValueAt(pos, 2)));
            this.txtEmail.setText((String) (tblNhanVien.getValueAt(pos, 3)));
            this.txtEmail.setEditable(true);
            int a = (int) tblModel.getValueAt(pos, 4);

            if (a == 1) {
                rdoQuanly.setSelected(true);
                rdoNhanVien.setSelected(false);

            } else {
                rdoQuanly.setSelected(false);
                rdoNhanVien.setSelected(true);
            }

        } catch (Exception e) {
        }
     }

    private void clearNV() {
        txtTenNV.setText("");
        txtEmail.setText("");
        rdoNhanVien.setSelected(false);
        rdoQuanly.setSelected(false);
        txtTenNV.setEditable(true);
        txtEmail.setEditable(true);
        txtTenNV.requestFocus();
    }

}
