/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPN;

import Controller.NumberOnlyFilter;
import DAO.SQLProvider;
import POJO.NhaCungCap;
import GUI.frmPhieuNhap;
import GUI.frmPhieuXuat;
import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author NGUYEN THANH THIEN
 */
public final class jpnNhaCungCap extends javax.swing.JPanel {
     private boolean isFormOpen = false;
    NhaCungCap ncc = new NhaCungCap();
    Vector<String> headerNCC = new Vector<>();
    Vector dataNCC = new Vector();
    DefaultTableModel tblModelNCC = new DefaultTableModel();

    String tennv;
    int manv;
    int vaitro;

    public jpnNhaCungCap(String tennv, int manv, int vaitro) {

        initComponents();
        this.tennv = tennv;
        this.manv = manv;
        this.vaitro = vaitro;

        tblModelNCC = (DefaultTableModel) this.tblNCC.getModel();

        //NHà chung cấp
        headerNCC.add("MÃ NCC");
        headerNCC.add("TÊN NCC");
        headerNCC.add("ĐỊA CHỈ");
        headerNCC.add("EMAIL");
        headerNCC.add("SỐ ĐIỆN THOẠI");
        LoadTableNhaCungCap();

        tblModelNCC.setDataVector(dataNCC, headerNCC);
        tblNCC.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tblNCC.getTableHeader().setOpaque(false);
        tblNCC.getTableHeader().setBackground(new Color(32, 136, 203));
        tblNCC.getTableHeader().setForeground(new Color(0, 0, 0));
        tblNCC.setRowHeight(40);

        TableColumnModel columnModel = tblNCC.getColumnModel();
        TableColumn column = columnModel.getColumn(0);
        column.setPreferredWidth(12);

        TableCellRenderer rendererFromHeader = tblNCC.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);

        tblNCC.getTableHeader().setDefaultRenderer(rendererFromHeader);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);

        for (int i = 0; i < tblNCC.getColumnCount(); i++) {
            tblNCC.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
        chondau();
        envent();

    }

    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=QL_BanHang";
    String user = "sa";
    String pass = "123";
    Statement st;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNCC = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtTenNCC = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        btnNhap = new javax.swing.JButton();
        btnXuat = new javax.swing.JButton();
        btnLamMoiNCC = new javax.swing.JButton();
        btnThemNCC = new javax.swing.JButton();
        btnXoaNCC = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnSuaNCC = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNCC = new javax.swing.JTable();

        setBackground(new java.awt.Color(60, 45, 81));
        setPreferredSize(new java.awt.Dimension(963, 751));

        jPanel1.setBackground(new java.awt.Color(60, 45, 81));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "THÔNG TIN NHÀ CUNG CẤP", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(0, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mã nhà cung cấp:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Email nhà cung cấp:");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tên nhà cung cấp:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Số điện thoại:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Địa chỉ:");

        txtNCC.setEditable(false);
        txtNCC.setBackground(new java.awt.Color(252, 218, 209));
        txtNCC.setFont(new java.awt.Font("Segoe WP", 0, 16)); // NOI18N
        txtNCC.setEnabled(false);

        txtSDT.setBackground(new java.awt.Color(252, 218, 209));
        txtSDT.setFont(new java.awt.Font("Segoe WP", 0, 16)); // NOI18N

        txtTenNCC.setBackground(new java.awt.Color(252, 218, 209));
        txtTenNCC.setFont(new java.awt.Font("Segoe WP", 0, 16)); // NOI18N

        txtEmail.setBackground(new java.awt.Color(252, 218, 209));
        txtEmail.setFont(new java.awt.Font("Segoe WP", 0, 16)); // NOI18N

        txtDiachi.setBackground(new java.awt.Color(252, 218, 209));
        txtDiachi.setFont(new java.awt.Font("Segoe WP", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-import-50_1.png"))); // NOI18N
        btnNhap.setText("NHẬP HÀNG");
        btnNhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhapMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhapMouseExited(evt);
            }
        });
        btnNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapActionPerformed(evt);
            }
        });

        btnXuat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconButtom/icons8-export-50 (1).png"))); // NOI18N
        btnXuat.setText("XUẤT HÀNG");
        btnXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnXuatMouseExited(evt);
            }
        });
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        btnLamMoiNCC.setBackground(new java.awt.Color(239, 225, 225));
        btnLamMoiNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLamMoiNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconMain/icons8-add-user-male-48.png"))); // NOI18N
        btnLamMoiNCC.setText("THÊM ĐÔI TÁC");
        btnLamMoiNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLamMoiNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiNCCActionPerformed(evt);
            }
        });

        btnThemNCC.setBackground(new java.awt.Color(239, 225, 225));
        btnThemNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThemNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconMain/icons8-checked-user-male-48.png"))); // NOI18N
        btnThemNCC.setText("  LƯU ĐỐI TÁC");
        btnThemNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNCCActionPerformed(evt);
            }
        });

        btnXoaNCC.setBackground(new java.awt.Color(239, 225, 225));
        btnXoaNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXoaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconMain/icons8-denied-48.png"))); // NOI18N
        btnXoaNCC.setText("  XÓA ĐỐI TÁC");
        btnXoaNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNCCActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconMain/icons8-restart-25.png"))); // NOI18N

        btnSuaNCC.setBackground(new java.awt.Color(239, 225, 225));
        btnSuaNCC.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSuaNCC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconMain/icons8-account-48.png"))); // NOI18N
        btnSuaNCC.setText("   SỬA ĐỐI TÁC");
        btnSuaNCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSuaNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNCCActionPerformed(evt);
            }
        });

        tblNCC.setFont(new java.awt.Font("Segoe WP Semibold", 0, 16)); // NOI18N
        tblNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblNCC.setFillsViewportHeight(true);
        tblNCC.setFocusable(false);
        tblNCC.setRowHeight(30);
        tblNCC.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tblNCC.getTableHeader().setReorderingAllowed(false);
        tblNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNCCMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblNCC);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLamMoiNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6))
                    .addComponent(btnSuaNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 89, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addComponent(btnXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnLamMoiNCC)
                        .addGap(24, 24, 24)
                        .addComponent(btnXoaNCC)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSuaNCC))
                        .addGap(18, 18, 18)
                        .addComponent(btnThemNCC))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhap)
                    .addComponent(btnXuat))
                .addGap(14, 14, 14))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNCCMouseClicked
        // TODO add your handling code here:
        int pos = tblNCC.getSelectedRow();
        this.txtNCC.setText("" + tblModelNCC.getValueAt(pos, 0));
        this.txtTenNCC.setText((String) (tblNCC.getValueAt(pos, 1)));
        this.txtDiachi.setText((String) (tblNCC.getValueAt(pos, 2)));
        this.txtEmail.setText((String) (tblNCC.getValueAt(pos, 3)));
        this.txtSDT.setText((String) (tblNCC.getValueAt(pos, 4)));
    }//GEN-LAST:event_tblNCCMouseClicked

    private void btnLamMoiNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiNCCActionPerformed
        // TODO add your handling code here:

       clearNCC();
    }//GEN-LAST:event_btnLamMoiNCCActionPerformed

    private void btnThemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNCCActionPerformed
        // TODO add your handling code here:
        String tenNCC = txtTenNCC.getText().trim();
        String diachi = txtDiachi.getText().trim();
        String email = txtEmail.getText().trim();
        String sdt = txtSDT.getText().trim();
        if(tenNCC.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Tên nhà cung cấp không được để trống");
        }
        
         else if(diachi.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Địa chỉ nhà cung cấp không được để trống");
        }
         else if(sdt.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "SĐT không được để trống");
        } else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email nhà cung cấp không được để trống");
        } else if (KT_NhaCC(email, sdt)) {
            JOptionPane.showMessageDialog(this, "Nhà cung cấp đã tồn tại vui lòng xem lại");

        } else {
            this.InsertNhaCungCap();
        }
        
    }//GEN-LAST:event_btnThemNCCActionPerformed

    private void btnNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapActionPerformed
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "Select *from NhanVien where MaNV = " + manv + "";
            PreparedStatement ps = con.prepareStatement(sql);
            rs = ps.executeQuery();

            if (rs.next()) {
                frmPhieuNhap nhap = new frmPhieuNhap(
                        rs.getInt("MaNV"),
                        rs.getString("TenNV"),
                        rs.getInt("Vaitro")
                );
               

                    nhap.setVisible(true);

                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnNhapActionPerformed

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, pass);
            String sql = "Select *from NhanVien where MaNV = " + manv + "";
            PreparedStatement ps = con.prepareStatement(sql);

            rs = ps.executeQuery();

            if (rs.next()) {
                frmPhieuXuat xuat = new frmPhieuXuat(
                        rs.getInt("MaNV"),
                        rs.getString("TenNV"),
                        rs.getInt("Vaitro")
                );
               

                    xuat.setVisible(true);

                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnXuatActionPerformed

    private void btnXoaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNCCActionPerformed
        try {
            int pos = tblNCC.getSelectedRow();
            if(pos  < 0)
            {
                 JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung cấp cần xoá");
            }
            else
            {
                 int maNCC = (int) tblNCC.getValueAt(pos, 0);
            if (JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa Mã nhà cung cấp :" + maNCC, "Thông báo", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                this.deleteNhaCungCap();
            }
            }
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }

    }//GEN-LAST:event_btnXoaNCCActionPerformed

    private void btnSuaNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNCCActionPerformed
        int pos = tblNCC.getSelectedRow();
         if(pos  < 0)
            {
                 JOptionPane.showMessageDialog(this, "Vui lòng chọn nhà cung cấp cần sửa");
            }
            else
            {
            try {
                this.updateNhaCungCap();
                clearNCC();
            } catch (IOException ex) {
                Logger.getLogger(jpnNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
        
    }//GEN-LAST:event_btnSuaNCCActionPerformed

    private void btnNhapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapMouseEntered
        // TODO add your handling code here:
        btnNhap.setBackground(new Color(0,255,255));
    }//GEN-LAST:event_btnNhapMouseEntered

    private void btnNhapMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhapMouseExited
        // TODO add your handling code here:
         btnNhap.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnNhapMouseExited

    private void btnXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatMouseEntered
        // TODO add your handling code here:
        btnXuat.setBackground(new Color(0,255,255));
    }//GEN-LAST:event_btnXuatMouseEntered

    private void btnXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXuatMouseExited
        // TODO add your handling code here:
         btnXuat.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnXuatMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoiNCC;
    private javax.swing.JButton btnNhap;
    private javax.swing.JButton btnSuaNCC;
    private javax.swing.JButton btnThemNCC;
    private javax.swing.JButton btnXoaNCC;
    private javax.swing.JButton btnXuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblNCC;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNCC;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNCC;
    // End of variables declaration//GEN-END:variables

    private void LoadTableNhaCungCap() {
        Vector<NhaCungCap> dsncc = DAO.DAO_NhaCungCap.DS_NhaCungCap();
        for (NhaCungCap ncc : dsncc) {
            Vector v = new Vector();
            v.add(ncc.getMaNCC());
            v.add(ncc.getTenNCC());
            v.add(ncc.getDiaChi());
            v.add(ncc.getEmail());
            v.add(ncc.getSdt());
            dataNCC.add(v);
        }
    }

    public void InsertNhaCungCap() {
        String tenNCC = txtTenNCC.getText().trim();
        String diachi = txtDiachi.getText().trim();
        String email = txtEmail.getText().trim();
        String sdt = txtSDT.getText().trim();
        boolean KT = DAO.DAO_NhaCungCap.InsertNhaCungCap(tenNCC, diachi, email, sdt);
        if (KT) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
        }
        tblModelNCC.setRowCount(0);
        LoadTableNhaCungCap();
        tblNCC.updateUI();
    }

    private void deleteNhaCungCap() throws IOException {
        int pos = tblNCC.getSelectedRow();
        int maNCC = (int) tblNCC.getValueAt(pos, 0);

        boolean KT = DAO.DAO_NhaCungCap.DeleteNhaCungCap(maNCC);
        if (KT) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
        }
        tblModelNCC.setRowCount(0);
        LoadTableNhaCungCap();
        tblNCC.updateUI();
    }

    private void updateNhaCungCap() throws IOException {
        int pos = tblNCC.getSelectedRow();
        int maNCC = (int) tblNCC.getValueAt(pos, 0);

        String tenNCC = txtTenNCC.getText().trim();
        String diachi = txtDiachi.getText().trim();
        String sdt = txtSDT.getText().trim();
        String email = txtEmail.getText().trim();

        boolean KT = DAO.DAO_NhaCungCap.UpdateNhaCungCap(maNCC, tenNCC, diachi, sdt, email);
        if (KT) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
        }
        tblModelNCC.setRowCount(0);
        LoadTableNhaCungCap();
        tblNCC.updateUI();
    }
    public boolean KT_NhaCC(String email, String sdt)
    {
        try {
            String sql = "Select *from NhaCungCap";
            SQLProvider ncc = new SQLProvider();
            ncc.open();
            ResultSet rs= ncc.executeQuery(sql);
            while(rs.next())
            {
                if(email.equalsIgnoreCase(rs.getString(4)) || sdt.equalsIgnoreCase(rs.getString(5)))
                    return true;
            }
        } catch (Exception e) {
        }
        return false;
    }
      public void chondau()
     {
          tblNCC.setRowSelectionInterval(0, 0);
        int pos = tblNCC.getSelectedRow();
        this.txtNCC.setText("" + tblModelNCC.getValueAt(pos, 0));
        this.txtTenNCC.setText((String) (tblNCC.getValueAt(pos, 1)));
        this.txtDiachi.setText((String) (tblNCC.getValueAt(pos, 2)));
        this.txtEmail.setText((String) (tblNCC.getValueAt(pos, 3)));
        this.txtSDT.setText((String) (tblNCC.getValueAt(pos, 4)));
     }

    private void envent() {
        ((AbstractDocument) txtSDT.getDocument()).setDocumentFilter(new NumberOnlyFilter());
    }

    private void clearNCC() {
        this.txtNCC.setText("");
        this.txtTenNCC.setText("");
        this.txtDiachi.setText("");
        this.txtEmail.setText("");
        this.txtSDT.setText("");

        this.txtTenNCC.requestFocus();
    }

}
